
//doctor
export const GET_ALL_DOCTOR = 'GET_ALL_DOCTOR'
export const GET_ALL_DOCTOR_SUCCESS = 'GET_ALL_DOCTOR_SUCCESS'
export const GET_ALL_DOCTOR_FAILED = 'GET_ALL_DOCTOR_FAILED'
export const UPDATE_DOCTOR = 'UPDATE_DOCTOR'
export const UPDATE_DOCTOR_FAILED = 'UPDATE_DOCTOR_FAILED'
export const UPDATE_DOCTOR_SUCCESS = 'UPDATE_DOCTOR_SUCCESS'
export const SET_STATE_MODAL_DOCTOR = 'SET_STATE_MODAL_DOCTOR';
export const GET_DOCTOR = 'GET_DOCTOR';
export const GET_DOCTOR_SUCCESS = 'GET_DOCTOR_SUCCESS';
export const GET_DOCTOR_FAILED = 'GET_DOCTOR_FAILED';

///patient
export const GET_ALL_PATIENT = 'GET_ALL_PATIENT'
export const GET_ALL_PATIENT_SUCCESS = 'GET_ALL_PATIENT_SUCCESS'
export const GET_ALL_PATIENT_FAILED = 'GET_ALL_PATIENT_FAILED'
export const UPDATE_PATIENT = 'UPDATE_PATIENT'
export const UPDATE_PATIENT_FAILED = 'UPDATE_PATIENT_FAILED'
export const UPDATE_PATIENT_SUCCESS = 'UPDATE_PATIENT_SUCCESS'
export const SET_STATE_MODAL_PATIENT = 'SET_STATE_MODAL_PATIENT';


///user
export const GET_ALL_USER = 'GET_ALL_USER'
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS'
export const GET_ALL_USER_FAILED = 'GET_ALL_USER_FAILED'
export const UPDATE_USER= 'UPDATE_USER'
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const SET_STATE_MODAL_USER = 'SET_STATE_MODAL_USER';
export const GET_USER = 'GET_USER'
export const GET_USER_FAILED = 'GET_USER_FAILED'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'