
//doctor
export const GET_ALL_DOCTOR = 'GET_ALL_DOCTOR'
export const GET_ALL_DOCTOR_SUCCESS = 'GET_ALL_DOCTOR_SUCCESS'
export const GET_ALL_DOCTOR_FAILED = 'GET_ALL_DOCTOR_FAILED'
export const UPDATE_DOCTOR = 'UPDATE_DOCTOR'
export const UPDATE_DOCTOR_FAILED = 'UPDATE_DOCTOR_FAILED'
export const UPDATE_DOCTOR_SUCCESS = 'UPDATE_DOCTOR_SUCCESS'
export const SET_STATE_MODAL_DOCTOR = 'SET_STATE_MODAL_DOCTOR';
export const GET_DOCTOR = 'GET_DOCTOR';
export const GET_DOCTOR_SUCCESS = 'GET_DOCTOR_SUCCESS';
export const GET_DOCTOR_FAILED = 'GET_DOCTOR_FAILED';
export const DELETE_DOCTOR = 'DELETE_DOCTOR'
export const DELETE_DOCTOR_SUCCESS = 'DELETE_DOCTOR_SUCCESS'
export const DELETE_DOCTOR_FAILED = 'DELETE_DOCTOR_FAILED'
export const RESTORE_DOCTOR = 'RESTORE_DOCTOR'
export const RESTORE_DOCTOR_SUCCESS = 'RESTORE_DOCTOR_SUCCESS'
export const RESTORE_DOCTOR_FAILED = 'RESTORE_DOCTOR_FAILED'
export const FETCH_DOCTOR_ACTIVE = 'FETCH_DOCTOR_ACTIVE'
export const FETCH_DOCTOR_ACTIVE_SUCCESS = 'FETCH_DOCTOR_ACTIVE_SUCCESS'
export const FETCH_DOCTOR_ACTIVE_FAILED = 'FETCH_DOCTOR_ACTIVE_FAILED'

///patient
export const GET_ALL_PATIENT = 'GET_ALL_PATIENT'
export const GET_ALL_PATIENT_SUCCESS = 'GET_ALL_PATIENT_SUCCESS'
export const GET_ALL_PATIENT_FAILED = 'GET_ALL_PATIENT_FAILED'
export const UPDATE_PATIENT = 'UPDATE_PATIENT'
export const UPDATE_PATIENT_FAILED = 'UPDATE_PATIENT_FAILED'
export const UPDATE_PATIENT_SUCCESS = 'UPDATE_PATIENT_SUCCESS'
export const SET_STATE_MODAL_PATIENT = 'SET_STATE_MODAL_PATIENT';
export const DELETE_PATIENT = 'DELETE_PATIENT'
export const DELETE_PATIENT_SUCCESS = 'DELETE_PATIENT_SUCCESS'
export const DELETE_PATIENT_FAILED = 'DELETE_PATIENT_FAILED'
export const RESTORE_PATIENT = 'RESTORE_PATIENT'
  

///user
export const GET_ALL_USER = 'GET_ALL_USER'
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS'
export const GET_ALL_USER_FAILED = 'GET_ALL_USER_FAILED'
export const UPDATE_USER= 'UPDATE_USER'
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const SET_STATE_MODAL_USER = 'SET_STATE_MODAL_USER';
export const GET_USER = 'GET_USER'
export const GET_USER_FAILED = 'GET_USER_FAILED'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const DELETE_USER = 'DELETE_USER'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED'
export const RESTORE_USER = 'RESTORE_USER'
export const RESTORE_USER_SUCCESS = 'RESTORE_USER_SUCCESS'
export const RESTORE_USER_FAILED = 'RESTORE_USER_FAILED'
export const CREATE_USER = 'CREATE_USER'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED'
export const GET_DOCTOR_BY_USER = 'GET_DOCTOR_BY_USER'
export const GET_DOCTOR_BY_USER_SUCCESS = 'GET_DOCTOR_BY_USER_SUCCESS'
export const GET_DOCTOR_BY_USER_FAILED = 'GET_DOCTOR_BY_USER_FAILED'
export const GET_PATIENT_BY_USER = 'GET_PATIENT_BY_USER'
export const GET_PATIENT_BY_USER_SUCCESS = 'GET_PATIENT_BY_USER_SUCCESS'
export const GET_PATIENT_BY_USER_FAILED = 'GET_PATIENT_BY_USER_FAILED'

export const UPDATE_PROFILE_DOCTOR = 'UPDATE_PROFILE_DOCTOR'
export const UPDATE_PROFILE_DOCTOR_SUCCESS = 'UPDATE_PROFILE_DOCTOR_SUCCESS'
export const UPDATE_PROFILE_DOCTOR_FAILED = 'UPDATE_PROFILE_DOCTOR_FAILED'
export const UPDATE_PROFILE_PATIENT = 'UPDATE_PROFILE_PATIENT'
export const UPDATE_PROFILE_PATIENT_SUCCESS = 'UPDATE_PROFILE_PATIENT_SUCCESS'
export const UPDATE_PROFILE_PATIENT_FAILED = 'UPDATE_PROFILE_PATIENT_FAILED'


//page client
export const SET_MODAL_INFO_USER = 'SET_MODAL_INFO_USER'
export const SET_MODAL_INFO_USER_SUCCESS = 'SET_MODAL_INFO_USER_SUCCESS'
export const SET_MODAL_INFO_USER_FAILED = 'SET_MODAL_INFO_USER_FAILED'

export const UPDATE_USER_INFO = "UPDATE_USER_INFO"
export const UPDATE_USER_INFO_SUCCESS = "UPDATE_USER_INFO_SUCCESS"
export const UPDATE_USER_INFO_FAILED = "UPDATE_USER_INFO_FAILED"

///Schedule
export const GET_ALL_SCHEDULE = 'GET_ALL_SCHEDULE'
export const GET_ALL_SCHEDULE_SUCCESS = 'GET_ALL_SCHEDULE_SUCCESS'
export const GET_ALL_SCHEDULE_FAILED = 'GET_ALL_SCHEDULE_FAILED'
export const DELETE_SCHEDULE = 'DELETE_SCHEDULE'
export const DELETE_SCHEDULE_SUCCESS = 'DELETE_SCHEDULE_SUCCESS'
export const DELETE_SCHEDULE_FAILED = 'DELETE_SCHEDULE_FAILED'
export const RESTORE_SCHEDULE = 'RESTORE_SCHEDULE'
export const CREATE_SCHEDULE = 'CREATE_SCHEDULE'
export const CREATE_SCHEDULE_SUCCESS = 'CREATE_SCHEDULE_SUCCESS'
export const CREATE_SCHEDULE_FAILED = 'CREATE_SCHEDULE_FAILED'
export const UPDATE_STATUS_SCHEDULE = 'UPDATE_STATUS_SCHEDULE'
export const UPDATE_STATUS_SCHEDULE_SUCCESS = 'UPDATE_STATUS_SCHEDULE_SUCCESS'
export const UPDATE_STATUS_SCHEDULE_FAILED = 'UPDATE_STATUS_SCHEDULE_FAILED'
export const SEND_SCHEDULE = 'SEND_SCHEDULE'
export const SEND_SCHEDULE_SUCCESS = 'SEND_SCHEDULE_SUCCESS'
export const SEND_SCHEDULE_FAILED = 'SEND_SCHEDULE_FAILED'
export const CANCEL_SCHEDULE = "CANCEL_SCHEDULE"
export const CANCEL_SCHEDULE_SUCCESS = "CANCEL_SCHEDULE_SUCCESS"
export const CANCEL_SCHEDULE_FAILED = "CANCEL_SCHEDULE_FAILED"


//auth
export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED'
export const AUTH_REGISTER = 'AUTH_REGISTER'
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS'
export const AUTH_REGISTER_FAILED = 'AUTH_REGISTER_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

//booking
export const CREATE_BOOKING = 'CREATE_BOOKING'
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS'
export const CREATE_BOOKING_FAILED = 'CREATE_BOOKING_FAILED'

export const CANCEL_BOOKING = 'CANCEL_BOOKING'
export const CANCEL_BOOKING_SUCCESS = 'CANCEL_BOOKING_SUCCESS'
export const CANCEL_BOOKING_FAILED = 'CANCEL_BOOKING_FAILED'

export const FETCH_BOOKING = 'FETCH_BOOKING'
export const FETCH_BOOKING_SUCCESS = 'FETCH_BOOKING_SUCCESS'
export const FETCH_BOOKING_FAILED = 'FETCH_BOOKING_FAILED'


//result
export const SAVE_RESULT = 'SAVE_RESULT';
export const SAVE_RESULT_SUCCESS = 'SAVE_RESULT_SUCCESS';
export const SAVE_RESULT_FAILED = 'SAVE_RESULT_FAILED';

export const FETCH_RESULT = 'FETCH_RESULT';
export const FETCH_RESULT_SUCCESS = 'FETCH_RESULT_SUCCESS';
export const FETCH_RESULT_FAILED = 'FETCH_RESULT_FAILED';

export const UPDATE_RESULT = 'UPDATE_RESULT'
export const UPDATE_RESULT_SUCCESS = 'UPDATE_RESULT_SUCCESS';
export const UPDATE_RESULT_FAILED = 'UPDATE_RESULT_FAILED';

export const GET_RESULT_BY_SCHEDULE = 'GET_RESULT_BY_SCHEDULE';
export const GET_RESULT_BY_SCHEDULE_SUCCESS = 'GET_RESULT_BY_SCHEDULE_SUCCESS';
export const GET_RESULT_BY_SCHEDULE_FAILED = 'GET_RESULT_BY_SCHEDULE_FAILED';

export const SET_MODAL_RESULT = 'SET_MODAL_RESULT'
export const SET_MODAL_RESULT_SUCCESS = 'SET_MODAL_RESULT_SUCCESS'
export const SET_MODAL_RESULT_FAILED = 'SET_MODAL_RESULT_FAILED'


export const FETCH_NOTIFICATION = 'FETCH_NOTIFICATION'
export const FETCH_NOTIFICATION_SUCCESS = 'FETCH_NOTIFICATION_SUCCESS'
export const FETCH_NOTIFICATION_FAILED = 'FETCH_NOTIFICATION_FAILED'

export const UPDATE_SEEN = 'UPDATE_SEEN'
export const UPDATE_SEEN_SUCCESS = 'UPDATE_SEEN_SUCCESS'
export const UPDATE_SEEN_FAILED = 'UPDATE_SEEN_FAILED'

export const GET_STATISTICAL = "GET_STATISTICAL";
export const GET_STATISTICAL_SUCCESS = "GET_STATISTICAL";
export const GET_STATISTICAL_FAILED = "GET_STATISTICAL";