
//doctor
export const GET_ALL_DOCTOR = 'GET_ALL_DOCTOR'
export const GET_ALL_DOCTOR_SUCCESS = 'GET_ALL_DOCTOR_SUCCESS'
export const GET_ALL_DOCTOR_FAILED = 'GET_ALL_DOCTOR_FAILED'
export const UPDATE_DOCTOR = 'UPDATE_DOCTOR'
export const UPDATE_DOCTOR_FAILED = 'UPDATE_DOCTOR_FAILED'
export const UPDATE_DOCTOR_SUCCESS = 'UPDATE_DOCTOR_SUCCESS'
export const SET_STATE_MODAL_DOCTOR = 'SET_STATE_MODAL_DOCTOR';
export const GET_DOCTOR = 'GET_DOCTOR';
export const GET_DOCTOR_SUCCESS = 'GET_DOCTOR_SUCCESS';
export const GET_DOCTOR_FAILED = 'GET_DOCTOR_FAILED';
export const DELETE_DOCTOR = 'DELETE_DOCTOR'
export const DELETE_DOCTOR_SUCCESS = 'DELETE_DOCTOR_SUCCESS'
export const DELETE_DOCTOR_FAILED = 'DELETE_DOCTOR_FAILED'
export const RESTORE_DOCTOR = 'RESTORE_DOCTOR'
export const RESTORE_DOCTOR_SUCCESS = 'RESTORE_DOCTOR_SUCCESS'
export const RESTORE_DOCTOR_FAILED = 'RESTORE_DOCTOR_FAILED'
export const FETCH_DOCTOR_ACTIVE = 'FETCH_DOCTOR_ACTIVE'
export const FETCH_DOCTOR_ACTIVE_SUCCESS = 'FETCH_DOCTOR_ACTIVE_SUCCESS'
export const FETCH_DOCTOR_ACTIVE_FAILED = 'FETCH_DOCTOR_ACTIVE_FAILED'

///patient
export const GET_ALL_PATIENT = 'GET_ALL_PATIENT'
export const GET_ALL_PATIENT_SUCCESS = 'GET_ALL_PATIENT_SUCCESS'
export const GET_ALL_PATIENT_FAILED = 'GET_ALL_PATIENT_FAILED'
export const UPDATE_PATIENT = 'UPDATE_PATIENT'
export const UPDATE_PATIENT_FAILED = 'UPDATE_PATIENT_FAILED'
export const UPDATE_PATIENT_SUCCESS = 'UPDATE_PATIENT_SUCCESS'
export const SET_STATE_MODAL_PATIENT = 'SET_STATE_MODAL_PATIENT';
export const DELETE_PATIENT = 'DELETE_PATIENT'
export const DELETE_PATIENT_SUCCESS = 'DELETE_PATIENT_SUCCESS'
export const DELETE_PATIENT_FAILED = 'DELETE_PATIENT_FAILED'
export const RESTORE_PATIENT = 'RESTORE_PATIENT'
  

///user
export const GET_ALL_USER = 'GET_ALL_USER'
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS'
export const GET_ALL_USER_FAILED = 'GET_ALL_USER_FAILED'
export const UPDATE_USER= 'UPDATE_USER'
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const SET_STATE_MODAL_USER = 'SET_STATE_MODAL_USER';
export const GET_USER = 'GET_USER'
export const GET_USER_FAILED = 'GET_USER_FAILED'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const DELETE_USER = 'DELETE_USER'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED'
export const RESTORE_USER = 'RESTORE_USER'
export const RESTORE_USER_SUCCESS = 'RESTORE_USER_SUCCESS'
export const RESTORE_USER_FAILED = 'RESTORE_USER_FAILED'